# Generated by Django 5.2.3 on 2025-07-01 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="learningrequestproposal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="learningrequestproposal",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="learningrequest",
            index=models.Index(
                fields=["student", "category"], name="learning_re_student_b005f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningrequestproposal",
            index=models.Index(
                fields=["mentor", "is_selected"], name="learning_re_mentor__dbf478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningrequestproposal",
            index=models.Index(
                fields=["request"], name="learning_re_request_28be30_idx"
            ),
        ),
    ]
