# Generated by Django 5.2.3 on 2025-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["type"], name="categories__type_60c7b7_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="categories__name_e3ad98_idx"),
        ),
    ]
