# Generated by Django 5.2.3 on 2025-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Main notification message to be shown."
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="Optional link to related content."
                    ),
                ),
                (
                    "unread",
                    models.BooleanField(
                        default=True, help_text="True if user hasn't opened yet."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
