# Generated by Django 5.2.3 on 2025-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_1014e9_idx",
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error")],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="unread",
            field=models.BooleanField(default=True),
        ),
    ]
