# Generated by Django 5.2.3 on 2025-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_initial"),
        ("mentors", "0007_mentorprofile_availability_slots_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("no_show", "No Show"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("mentor", "start_time", "end_time")},
        ),
    ]
