# Generated by Django 5.2.3 on 2025-06-27 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/photos/"
                    ),
                ),
                ("education", models.TextField(blank=True, null=True)),
                ("interests", models.TextField(blank=True, null=True)),
                ("learning_goals", models.TextField(blank=True, null=True)),
                (
                    "language_preference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
