# Generated by Django 5.2.3 on 2025-07-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studentprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
