# Generated by Django 5.2.3 on 2025-06-21 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("Live", "Live"),
                            ("PayPerMinute", "Pay-per-minute"),
                            ("Fixed", "Fixed-rate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rate_applied",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("student_confirmed", models.BooleanField(default=False)),
                ("mentor_confirmed", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
