# Generated by Django 5.2.3 on 2025-07-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.AddField(
            model_name="badge",
            name="expires_in_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional: Badge expires after X days from assignment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="level",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Optional badge level for hierarchy (1 = basic, 2 = advanced)",
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="note",
            field=models.CharField(
                blank=True, help_text="Optional note by admin", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="userbadge",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Whether this badge has been verified manually"
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="icon_url",
            field=models.URLField(
                blank=True, help_text="URL or static path to badge image"
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier for the badge (used internally)",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awarded_users",
                to="badges.badge",
            ),
        ),
    ]
