# Generated by Django 5.2.3 on 2025-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("scheduled_time", models.DateTimeField()),
                (
                    "duration_mins",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "twilio_room_sid",
                    models.CharField(
                        blank=True,
                        help_text="Twilio Room SID once the session is started",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Consultations",
                "ordering": ["-scheduled_time"],
            },
        ),
    ]
