# Generated by Django 5.2.3 on 2025-06-21 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations_as_student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["mentor", "scheduled_time"],
                name="consultatio_mentor__933777_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["student", "scheduled_time"],
                name="consultatio_student_ede96e_idx",
            ),
        ),
    ]
