# Generated by Django 5.2.3 on 2025-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Optional feedback after completion"
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True, help_text="Optional rating out of 5", null=True
            ),
        ),
    ]
