# Generated by Django 5.2.3 on 2025-06-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gigs", "0001_initial"),
        ("mentors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids_from_gigs_app",
                to="mentors.mentorprofile",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="bid",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_from_gigs_app",
                to="gigs.bid",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts_as_mentor_from_gigs_app",
                to="mentors.mentorprofile",
            ),
        ),
    ]
