# Generated by Django 5.2.3 on 2025-06-21 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("gigs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts_as_student_from_gigs_app",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gigrequest",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gigs_from_gigs_app",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="gigrequest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gigs_from_gigs_app",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="gig_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts_from_gigs_app",
                to="gigs.gigrequest",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="gig_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids_from_gigs_app",
                to="gigs.gigrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="gigrequest",
            index=models.Index(
                fields=["student", "status"], name="gigs_gigreq_student_39f798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gigrequest",
            index=models.Index(
                fields=["bidding_deadline"], name="gigs_gigreq_bidding_2b4833_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["mentor", "status"], name="gigs_bid_mentor__65e3c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["gig_request", "status"], name="gigs_bid_gig_req_c33163_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together={("gig_request", "mentor")},
        ),
    ]
