# Generated by Django 5.2.3 on 2025-06-21 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("mentors", "0003_mentorprofile_expertise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("Live", "Live 1:1"),
                            ("Recorded", "Recorded"),
                            ("Group", "Group Class"),
                            ("Project", "Short-term Project"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule_info",
                    models.JSONField(
                        blank=True, default=dict, help_text="e.g. {'slots': [...]}"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="categories.category",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courses",
                "ordering": ["-created_at"],
                "unique_together": {("title", "mentor")},
            },
        ),
    ]
