# Generated by Django 5.2.3 on 2025-06-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_duration_hours_alter_course_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="certificate_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="intro_pdf",
            field=models.FileField(blank=True, null=True, upload_to="courses/pdfs/"),
        ),
        migrations.AddField(
            model_name="course",
            name="preview_video",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CourseQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
