# Generated by Django 5.2.3 on 2025-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_categories__type_60c7b7_idx_and_more"),
        ("courses", "0003_course_certificate_available_course_intro_pdf_and_more"),
        ("mentors", "0006_mentorprofile_country_mentorprofile_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursequiz",
            name="course",
        ),
        migrations.AddField(
            model_name="course",
            name="enrollment_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Max students allowed", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enrollments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Auto-generated or custom URL slug", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="courses_cou_slug_2e551f_idx"),
        ),
        migrations.DeleteModel(
            name="CourseQuiz",
        ),
    ]
