# Generated by Django 5.2.3 on 2025-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_coursequiz_course_course_enrollment_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
