# Generated by Django 5.2.3 on 2025-07-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_auto_20250701_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
