# Generated by Django 5.2.3 on 2025-07-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
