# Generated by Django 5.2.3 on 2025-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="schedule_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="e.g. {'slots': ['Mon 5pm', 'Wed 7pm']}",
            ),
        ),
    ]
