# Generated by Django 5.2.3 on 2025-06-21 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mentor_reviews", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewee", "created_at"], name="mentor_revi_reviewe_d4e118_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "created_at"], name="mentor_revi_reviewe_954e3e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("reviewer", "reviewee", "created_at")},
        ),
    ]
