# Generated by Django 5.2.3 on 2025-06-22 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmembership",
            options={
                "verbose_name": "Chat Membership",
                "verbose_name_plural": "Chat Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="chatroom",
            options={"verbose_name": "Chat Room", "verbose_name_plural": "Chat Rooms"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["sent_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterField(
            model_name="chatmembership",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="chat.chatroom",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="chat_rooms",
                through="chat.ChatMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
    ]
