# Generated by Django 5.2.3 on 2025-06-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bids", "0001_initial"),
        ("gigs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="gig_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids_from_bids_app",
                to="gigs.gigrequest",
            ),
        ),
    ]
