# Generated by Django 5.2.3 on 2025-06-21 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bids", "0002_initial"),
        ("mentors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids_from_bids_app",
                to="mentors.mentorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["mentor", "status"], name="bids_bid_mentor__f54c28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["gig_request", "status"], name="bids_bid_gig_req_2f655c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together={("gig_request", "mentor")},
        ),
    ]
