# Generated by Django 5.2.3 on 2025-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="proposal_text",
            field=models.TextField(help_text="Explain your approach or value offer"),
        ),
    ]
