# Generated by Django 5.2.3 on 2025-07-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0004_alter_bid_proposal_text"),
        ("gigs", "0003_initial"),
        ("mentors", "0006_mentorprofile_country_mentorprofile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="gig_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="gigs.gigrequest",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="mentors.mentorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
