# Generated by Django 5.2.3 on 2025-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "per_minute_rate",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("rating", models.FloatField(default=0)),
                ("num_reviews", models.PositiveIntegerField(default=0)),
                ("certifications", models.TextField(blank=True)),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated ISO codes",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specialties",
                    models.ManyToManyField(
                        related_name="mentors", to="categories.category"
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "user__username"],
            },
        ),
    ]
