# Generated by Django 5.2.3 on 2025-06-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="expertise",
            field=models.CharField(default="General", max_length=255),
        ),
    ]
