# Generated by Django 5.2.3 on 2025-07-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mentors",
            "0004_mentorprofile_linkedin_url_mentorprofile_youtube_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_availability",
                        to="mentors.mentorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["mentor", "day", "start_time"],
                "unique_together": {("mentor", "day", "start_time", "end_time")},
            },
        ),
    ]
