# Generated by Django 5.2.3 on 2025-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0005_mentoravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="mentors/photos/"),
        ),
    ]
