# Generated by Django 5.2.3 on 2025-07-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0006_mentorprofile_country_mentorprofile_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="availability_slots",
            field=models.CharField(default="9AM-5PM", max_length=255),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="social_linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="social_youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
