# Generated by Django 5.2.3 on 2025-07-04 06:37

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_categories__type_60c7b7_idx_and_more"),
        ("mentors", "0007_mentorprofile_availability_slots_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorprofile",
            name="availability_slots",
        ),
        migrations.RemoveField(
            model_name="mentorprofile",
            name="social_linkedin",
        ),
        migrations.RemoveField(
            model_name="mentorprofile",
            name="social_youtube",
        ),
        migrations.AddField(
            model_name="availabilitywindow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="availabilitywindow",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mentorprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="certifications",
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="education",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="experience",
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="per_minute_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="rating",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="availabilitywindow",
            index=models.Index(
                fields=["mentor", "start", "end"], name="mentors_ava_mentor__db4dd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(
                fields=["rating", "is_active"], name="mentors_men_rating_fca417_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mentorprofile",
            index=models.Index(
                fields=["created_at"], name="mentors_men_created_3b7d5d_idx"
            ),
        ),
    ]
